import { createWindowInteriorAtlasEntry, WINDOW_INTERIOR_TYPE } from './_shared.js';

const atlas = createWindowInteriorAtlasEntry({
    id: 'window_interior_image.storefront_silhouette_2x2',
    label: 'Storefront Silhouette 2x2',
    fileName: 'parallax_interior_atlas_storefront_silhouette_2x2.png',
    type: WINDOW_INTERIOR_TYPE.BUSINESS,
    // A generic dark interior: soft shelf/counter silhouettes and faint lamp
    // glows, deliberately unreadable as any specific business.
    businessTypes: ['generic'],
    image: { widthPx: 1024, heightPx: 1024, hasAlpha: false },
    // Generated by tools/bradbury_generate_silhouette_atlas.mjs — the grid is
    // authored, not read off a photo collage.
    grid: { cols: 2, rows: 2 },
    borders: {
        edgeInsetPx: 6,
        gutterPx: { x: 0, y: 0 }
    }
});

export default atlas;
