// Exercises real asset loading, rendering, navigation and camera controls in the v2 baseline.
import test, { expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import { BIG_CITY_SPEC_SOURCE } from '../../../src/app/city/specs/BigCitySpec.js';

test('Grass Debug v2 loads game assets, exposes stats and preserves the v1 entry', async ({ page }) => {
    test.setTimeout(120_000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/debug_tools/grass_debug.html');
    await expect(page).toHaveURL(/grass_debug_v2\.html$/);
    await page.waitForFunction(() => !!window.__grassDebugV2, null, { timeout: 30_000 });
    await page.evaluate(() => window.__grassDebugV2.readiness);
    await page.waitForFunction(() => window.__grassDebugV2.getSnapshot().frame > 120);
    const snapshot = await page.evaluate(() => window.__grassDebugV2.getSnapshot());
    expect(snapshot.terrain.width).toBe(BIG_CITY_SPEC_SOURCE.width * BIG_CITY_SPEC_SOURCE.tileSize);
    expect(snapshot.terrain.depth).toBe(BIG_CITY_SPEC_SOURCE.height * BIG_CITY_SPEC_SOURCE.tileSize);
    expect(snapshot.groundTextureReady).toBe(true);
    expect(snapshot.roadTriangles).toBeGreaterThan(0);
    expect(snapshot.roadSurfaceY).toBeGreaterThan(snapshot.groundSurfaceY + 0.001);
    expect(snapshot.treeCount).toBe(12);
    expect(snapshot.busReady).toBe(true);
    expect(snapshot.camera.fov).toBe(55);
    expect(snapshot.render.calls).toBeGreaterThan(0);
    expect(snapshot.grass).toMatchObject({ implemented: true, mode: 'LOD0', leaves: 294912, triangles: 4128768, incrementalGpuMs: null, targetGpuMs: 1 });
    await expect(page.locator('.ui-perf-bar')).toBeVisible();
    await expect(page.locator('.ui-perf-debug-line')).toContainText('Camera: XYZ');
    await expect(page.locator('.ui-perf-debug-line')).toContainText('Bus: XYZ');
    await expect(page.locator('input, select')).toHaveCount(0);
    const artifacts = 'tests/artifacts/screens/grass_debug_v2';
    await mkdir(artifacts, { recursive: true });
    await page.screenshot({ path: `${artifacts}/bus-camera.png` });
    await writeFile(`${artifacts}/baseline.json`, JSON.stringify(snapshot, null, 2));
    for (const [key, axis, sign] of [['w', 2, 1], ['s', 2, -1], ['a', 0, 1], ['d', 0, -1], ['q', 1, -1], ['e', 1, 1]]) {
        await page.keyboard.press('1');
        await page.keyboard.down(key);
        await expect.poll(async () => {
            const position = await page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position);
            return (position[axis] - snapshot.camera.position[axis]) * sign;
        }).toBeGreaterThan(0.5);
        await page.keyboard.up(key);
    }
    await page.keyboard.down('q');
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position[1])).toBeCloseTo(0.01, 4);
    await page.keyboard.up('q');
    await page.keyboard.down('w');
    await page.evaluate(() => window.dispatchEvent(new Event('blur')));
    const stopped = await page.evaluate(() => window.__grassDebugV2.getSnapshot());
    await page.waitForFunction(frame => window.__grassDebugV2.getSnapshot().frame > frame + 5, stopped.frame);
    expect(await page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position)).toEqual(stopped.camera.position);
    await page.keyboard.up('w');
    await page.getByRole('button', { name: 'Overview' }).click();
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position.map(value => Number(value.toFixed(5))))).toEqual([19, 22, -22]);
    await expect(page.locator('.ui-perf-debug-line')).toContainText('Y/P/R° (138.0, -38.0, 0.0)');
    await page.screenshot({ path: `${artifacts}/overview.png` });
    await page.mouse.move(1000, 600);
    await page.mouse.down();
    await page.mouse.move(1000, 420, { steps: 12 });
    await page.mouse.up();
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position[1])).toBeCloseTo(0.01, 4);
    const lowCamera = await page.evaluate(() => window.__grassDebugV2.getSnapshot().camera);
    expect(lowCamera.near).toBeLessThan(0.01);
    await page.mouse.wheel(0, -500);
    await page.keyboard.down('Shift');
    await page.mouse.move(1000, 600);
    await page.mouse.down();
    await page.mouse.move(1000, 450, { steps: 12 });
    await page.mouse.up();
    await page.keyboard.up('Shift');
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position[1])).toBeGreaterThanOrEqual(0.01);
    await page.keyboard.press('1');
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position)).toEqual(snapshot.camera.position);
    await page.mouse.move(1000, 500);
    await page.mouse.down();
    await page.mouse.move(1120, 530, { steps: 8 });
    await page.mouse.up();
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().camera.position)).not.toEqual(snapshot.camera.position);
    await page.setViewportSize({ width: 1280, height: 720 });
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().viewport.width)).toBe(1040);
    await expect.poll(() => page.evaluate(() => window.__grassDebugV2.getSnapshot().viewport.height)).toBe(672);
    expect(errors).toEqual([]);
    await page.goto('/debug_tools/grass_debug_v1.html');
    await expect(page).toHaveURL(/grass_debug_v1\.html$/);
    await expect(page).toHaveTitle('Grass Debug v1');
    await page.waitForFunction(() => document.body.dataset.grassLabReady === 'true', null, { timeout: 60_000 });
    expect(await page.evaluate(() => !!window.__grassLab && !window.__grassDebugV2)).toBe(true);
});
