// src/graphics/gui/mesh_fabrication/errors/meshFabricationErrorCodes.js

export const MESH_FABRICATION_ERROR_CODE = Object.freeze({
    LOADER_TRANSPORT_FAILED: 'MF_LOADER_TRANSPORT_FAILED',
    LOADER_ENDPOINT_RESOLVE_FAILED: 'MF_LOADER_ENDPOINT_RESOLVE_FAILED',
    LOADER_PARSE_FAILED: 'MF_LOADER_PARSE_FAILED',
    PIPELINE_PARSE_FAILED: 'MF_PIPELINE_PARSE_FAILED',
    PIPELINE_NORMALIZE_FAILED: 'MF_PIPELINE_NORMALIZE_FAILED',
    PIPELINE_EXECUTE_FAILED: 'MF_PIPELINE_EXECUTE_FAILED',
    BOOLEAN_KERNEL_FAILED: 'MF_BOOLEAN_KERNEL_FAILED',
    VALIDATION_ERROR: 'MF_VALIDATION_ERROR',
    UNKNOWN: 'MF_UNKNOWN'
});

export const MESH_FABRICATION_ERROR_UI_MESSAGE = Object.freeze({
    [MESH_FABRICATION_ERROR_CODE.LOADER_TRANSPORT_FAILED]: 'Live mesh transport failed.',
    [MESH_FABRICATION_ERROR_CODE.LOADER_ENDPOINT_RESOLVE_FAILED]: 'Live mesh endpoint could not be resolved.',
    [MESH_FABRICATION_ERROR_CODE.LOADER_PARSE_FAILED]: 'Live mesh payload failed validation.',
    [MESH_FABRICATION_ERROR_CODE.PIPELINE_PARSE_FAILED]: 'Command parse stage failed.',
    [MESH_FABRICATION_ERROR_CODE.PIPELINE_NORMALIZE_FAILED]: 'Command normalize stage failed.',
    [MESH_FABRICATION_ERROR_CODE.PIPELINE_EXECUTE_FAILED]: 'Command execute stage failed.',
    [MESH_FABRICATION_ERROR_CODE.BOOLEAN_KERNEL_FAILED]: 'Boolean kernel execution failed.',
    [MESH_FABRICATION_ERROR_CODE.VALIDATION_ERROR]: 'Input validation failed.',
    [MESH_FABRICATION_ERROR_CODE.UNKNOWN]: 'Mesh fabrication operation failed.'
});
