// Build the local view-card comparison from measured timings and deterministic captures.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('tests/artifacts/screens/grass_debug_v2/transition_lab/view_cards_fidelity');
const benchmark = JSON.parse(await readFile(path.join(root, 'benchmark.json'), 'utf8'));
const visual = JSON.parse(await readFile(path.join(root, 'visual.json'), 'utf8'));
const names = { geometry: 'Original LOD3 leaves', cards: 'Revised 20 cards/m²' };
const quality = ['lod2', 'previous-cards', 'cards'].map(mode => {
    const samples = visual.rows.filter(row => row.mode === mode).flatMap(row => row.coverage.filter(band => band.near < 18));
    const average = getter => samples.reduce((sum, sample) => sum + getter(sample), 0) / samples.length;
    return { mode, coverage: average(sample => sample.coverage), rgb: [0, 1, 2].map(c => average(sample => sample.leafRgb[c])), holes: average(sample => sample.lowCoverageBlockFraction) };
}).filter(row => Number.isFinite(row.coverage));
const modes = benchmark.metadata.versions, number = value => value.toFixed(3);
const rows = Object.entries(benchmark.comparisons).map(([key, comparison]) => `<tr><td>${key.replaceAll('_', ' ')}</td>${modes.map(mode => {
    const result = comparison.results[mode].aboveSoilGpu;
    return `<td title="95% interval: ${result.ci95Ms.map(number).join('–')} ms">${number(result.averageMs)}</td>`;
}).join('')}</tr>`).join('');
const means = Object.fromEntries(modes.map(mode => [mode, ['front', 'rear', 'border'].reduce((sum, pose) => sum + benchmark.comparisons['full_' + pose].results[mode].aboveSoilGpu.averageMs / 3, 0)]));
const cards = visual.rows.find(row => row.snapshot?.viewCards)?.snapshot.viewCards;
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>LOD3 · Closer leaf shapes · 25 cm cards</title>
<style>body{margin:0;padding:28px;background:#13241c;color:#ecf1e6;font:17px system-ui}main{max-width:1500px;margin:auto}h1{font-size:30px}p{max-width:1050px;line-height:1.55}a{color:#b9db94}select,button,input{font:inherit;padding:8px;background:#253b2d;color:inherit;border:1px solid #80947c;border-radius:6px}label{display:inline-flex;gap:8px;align-items:center;margin:10px 16px 10px 0}.split{position:relative;width:100%;background:#09150e}.split img{display:block;width:100%}.split .overlay{position:absolute;inset:0;clip-path:inset(0 50% 0 0)}.tag{position:absolute;top:12px;padding:10px;background:#14241bd9}.right{right:12px}.left{left:12px}table{border-collapse:collapse;margin:20px 0;font-variant-numeric:tabular-nums}td,th{border:1px solid #64715d;padding:10px 18px;text-align:right}td:first-child,th:first-child{text-align:left}details{padding:10px 0}.motion{width:100%}output{min-width:80px}small{color:#becbb5}</style>
<main><h1>LOD3 · Closer leaf shapes · 25 cm cards</h1>
<p>Twenty 25 cm cards replace ten 50 cm cards per square metre. Narrower groups and a 30° source view preserve more of the leaning leaf silhouettes. Each rotating card keeps one sharp image instead of cross-fading different leaves. A constant material tint matches front, side and rear lighting. The LOD2-to-card band uses multisample coverage to remove the visible screen-door stipple. Original LOD3 leaves remain available and are still the default.</p>
<p><b>Measured full-scene grass cost above soil:</b> ${modes.map(mode => `${names[mode]} ${number(means[mode])} ms`).join(' · ')}. The revised cards save ${((1 - means.cards / means.geometry) * 100).toFixed(1)}% on this paired run. Texture allocation stays at 67.1 MB including mipmaps. No extra ground texture or per-frame captures are used.</p>
<p><a href="/debug_tools/grass_transition_scene.html?revision=lod3-fidelity-1&lod3=cards#front">Open live experiment · 20 cards/m²</a> · <a href="benchmark.json">Raw benchmark</a> · <a href="visual.json">Capture metadata</a></p>
<h2>Close shape and transition check</h2><p>Camera height 2 m, tilt 30°. This deliberately stresses the near boundary and leaf shapes, beyond the normal bus-view comparison. Slide the shared split control to compare.</p><label>Bearing <select id="close-bearing"><option>0</option><option>90</option><option>180</option></select>°</label><label>Reference <select id="close-reference"><option value="lod2">LOD2 leaves</option>${visual.previousClose?.length ? '<option value="previous-cards">Previous cards</option><option value="previous-transition">Previous transition</option>' : ''}</select></label><label>Split <input id="close-split" type="range" min="0" max="100" value="50"></label><div class="split"><img id="close-original" alt="Close reference"><img class="overlay" id="close-cards" alt="Revised close view"><span class="tag left">Revised</span><span class="tag right" id="close-label">LOD2</span></div>
<h2>Coverage and leaf color</h2><p>Fixed green-pixel classification inside field interiors, split into 6–10, 10–14 and 14–18 m camera-distance bands. Equal averages of those bands across 14/24 m field-centre positions and 0/45/90/180° bearings. Color uses only classified grass pixels; paths, sky and field edges are excluded. These are screen-space proxies, not semantic masks or a claim of visual equivalence.</p>
<table><tr><th>Version</th><th>Green coverage</th><th>Grass-only RGB / 255</th><th>Low-coverage blocks</th></tr>${quality.map(row => `<tr><td>${({lod2:'LOD2 reference','previous-cards':'Previous 10 cards/m²',cards:'Revised 20 cards/m²'})[row.mode]}</td><td>${(row.coverage * 100).toFixed(1)}%</td><td>${row.rgb.map(v => v.toFixed(1)).join(' / ')}</td><td>${(row.holes * 100).toFixed(2)}%</td></tr>`).join('')}</table>
<p>Low-coverage blocks are 32-pixel squares with less than 70% of their distance band's mean green coverage. Coverage averages alone did not expose the previous silhouette problem, so the close views above are the main fidelity check. Fine detail still lacks true per-leaf parallax; some clumps and repetition remain. The older card captures are historical visual evidence, not a fresh performance baseline.</p>
<h2>Real transition scene</h2><label>Pose <select id="pose"><option>front</option><option>rear</option><option>border</option></select></label><label>Cards <select id="mode">${modes.filter(mode => mode !== 'geometry').map(mode => `<option value="${mode}">${names[mode]}</option>`).join('')}</select></label><label>Split <input id="split" type="range" value="50" min="0" max="100"></label>
<div class="split"><img id="original" alt="Original LOD3 in the full transition scene"><img class="overlay" id="cards" alt="Experimental cards in the same scene"><span class="tag left" id="mode-label"></span><span class="tag right">Original LOD3</span></div>
<h2>Same-height bus views · all fields forced to one LOD</h2><p>The distance is measured to the field centre. The foreground is closer; this deliberately reveals limits outside the intended band.</p>
<label>Distance <select id="distance"><option>14</option><option>24</option></select> m</label><label>Bearing <select id="bearing"><option>0</option><option>45</option><option>90</option><option>180</option></select>°</label><label>Reference <select id="reference"><option value="lod2">LOD2</option><option value="geometry">Original LOD3</option><option value="previous-cards">Previous cards</option></select></label>
<div class="split"><img id="bus-original" alt="Geometric reference at bus height"><img class="overlay" id="bus-cards" alt="Same pose with cards"><span class="tag left">Selected cards</span><span class="tag right" id="ref-label">LOD2</span></div>
<h2>Camera turning</h2><p>20 cards/m², camera orbit 30–60° at fixed bus height and tilt. No additional captures, batch updates or texture uploads are scheduled by card orientation.</p><button id="play">Play / pause</button><label>Frame <input id="motion" type="range" min="0" max="30" value="0"><output id="angle">30°</output></label><img class="motion" id="turn" src="turn_0.jpg" alt="Camera orbit sequence">
<h2>Moving through the near transition</h2><p>Close camera advances two metres in 10 cm steps, with real LOD selection. No rebaking. The multisample fade is a depth-writing coverage approximation, so slight density changes can remain.</p><label>Frame <input id="drive" type="range" min="0" max="10" value="0"></label><img class="motion" id="drive-image" src="drive_0.png" alt="Movement through the LOD2 to LOD3 transition">
<h2>Performance</h2><p>1920 × 1080, DPR 1. Values are GPU milliseconds <b>above matched soil-only rendering</b>. “full” includes all distance LODs and blending; “lod3-only” isolates the representation over every field. Shadows stay enabled and cached. Hover a cell for its 95% interval.</p><table><thead><tr><th>Configuration / pose</th>${modes.map(mode => `<th>${names[mode]}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>
<p>Moving selection + batch updates average ${benchmark.metadata.versions.map(mode => names[mode] + ": " + (benchmark.cpuMotion.filter(row => row.version === mode).reduce((sum, row) => sum + row.selectionCpuMs + row.batchCpuMs, 0) / (3 * 60)).toFixed(3) + " ms/frame").join(" · ")}. This small difference is not a proven CPU speedup. Static timed blocks perform zero selection scans, instance uploads or shadow regenerations.</p><p>Added atlas memory: <b>${(cards.textureBytes / 1e6).toFixed(1)} MB (${(cards.textureBytes / 1048576).toFixed(0)} MiB)</b> including mipmaps, shared by all fields and the 10/20/32 density options. Only the revised 20/m² mode is compared here. Three uncompressed maps, 32 tiles of 512 × 256 pixels. This excludes existing soil/canopy, frame buffers and cached scene shadows. Capture time in the visual run: ${(cards.captureMilliseconds / 1000).toFixed(2)} s; first-use shader compilation and GPU upload are additional.</p>
<details><summary>Measurement method and limits</summary><p>${benchmark.metadata.method}</p><p>${benchmark.metadata.renderer}. ${benchmark.metadata.browser}.</p><p>Captures use one 30° elevation and have no depth reprojection. Cards retain a fixed source image while rotating, including their captured normal basis. They cannot recover true per-leaf parallax or exact world-fixed blade lighting. Close/steep views still differ from LOD2; this is an improvement, not visual equivalence. Shadow reception uses the existing geometric shadow cache; cards do not cast new dynamic grass shadows. Clocks and desktop load were not locked; compare variants within this paired run, not absolute timings from different sessions.</p></details></main>
<script>const byId=id=>document.getElementById(id), names=${JSON.stringify(names)}; function update(){const pose=byId('pose').value, mode=byId('mode').value, distance=byId('distance').value, bearing=byId('bearing').value, ref=byId('reference').value;  byId('original').src='full_'+pose+'_geometry.png';byId('cards').src='full_'+pose+'_'+mode+'.png';byId('mode-label').textContent=names[mode];byId('bus-original').src=(ref==='previous-cards'?'../view_cards_coverage/':'')+'bus_'+distance+'_'+bearing+'_'+(ref==='previous-cards'?'cards':ref)+'.png';byId('bus-cards').src='bus_'+distance+'_'+bearing+'_'+mode+'.png';byId('ref-label').textContent=ref==='lod2'?'LOD2':ref==='previous-cards'?'Previous cards':'Original LOD3';document.querySelectorAll('.overlay:not(#close-cards)').forEach(image=>image.style.clipPath='inset(0 '+(100-byId('split').value)+'% 0 0)');}['pose','mode','distance','bearing','reference','split'].forEach(id=>byId(id).addEventListener('input',update));update(); const frames=Array.from({length:31},(_,i)=>{const image=new Image();image.src='turn_'+(i*2)+'.jpg';return image;});let playing=false;function motion(){const i=Number(byId('motion').value);byId('turn').src=frames[i].src;byId('angle').textContent=(30+i)+'°';}byId('motion').addEventListener('input',motion);byId('play').onclick=()=>playing=!playing;setInterval(()=>{if(playing){byId('motion').value=(Number(byId('motion').value)+1)%31;motion();}},100);function closeView(){const b=byId('close-bearing').value,r=byId('close-reference').value,transition=r==='previous-transition';byId('close-original').src=r==='lod2'?'close_'+b+'_lod2.png':'previous_close_'+b+'_'+(transition?'transition':'cards')+'.png';byId('close-cards').src='close_'+b+'_'+(transition?'transition':'cards')+'.png';byId('close-label').textContent=byId('close-reference').selectedOptions[0].text;byId('close-cards').style.clipPath='inset(0 '+(100-byId('close-split').value)+'% 0 0)';}['close-bearing','close-reference','close-split'].forEach(id=>byId(id).addEventListener('input',closeView));closeView();byId('drive').addEventListener('input',()=>byId('drive-image').src='drive_'+(Number(byId('drive').value)*2)+'.png');</script></html>`;
await writeFile(path.join(root, 'index.html'), html);
console.log(root);
