// Build a reproducible comparison from the fade-style and moving-camera captures.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('tests/artifacts/screens/grass_debug_v2/transition_lab/fade_styles');
const comparison = JSON.parse(await readFile(path.join(root, 'comparison.json'), 'utf8'));
const movement = JSON.parse(await readFile(path.join(root, 'blending/visual.json'), 'utf8'));
const names = {coverage:'Previous coverage fade',alpha:'Plain alpha',staggered:'Staggered cards',dissolve:'Opaque dissolve'};
const color = Object.keys(names).map(style => {
    const rows = comparison.rows.filter(r=>r.style===style), errors=[];
    for(const row of rows) for(const band of row.coverage.filter(b=>b.near>=10&&b.far<=14)) {
        const ends=['lod3','lod4'].map(level=>comparison.rows.find(r=>r.pose===row.pose&&r.style===level).coverage.find(b=>b.near===band.near));
        const distance=(band.near+band.far)/2,t=Math.max(0,Math.min(1,(distance-8.5)/7.5)),w=t*t*(3-2*t);
        errors.push(Math.abs(band.leafRgb[1]-(ends[0].leafRgb[1]*(1-w)+ends[1].leafRgb[1]*w)));
    }
    return '<tr><td>'+names[style]+'</td><td>'+(errors.reduce((a,b)=>a+b,0)/errors.length).toFixed(2)+'</td></tr>';
}).join('');
const motion=movement.motion.filter(r=>r.mode==='blend').map(row=>{
    const sum=mode=>movement.motion.find(r=>r.pose===row.pose&&r.mode===mode).frames.reduce((a,f)=>a+(f.rebuildChangedPixels||0),0);
    return '<tr><td>'+row.pose+'</td><td>'+sum('blend').toLocaleString()+'</td><td>'+sum('patches').toLocaleString()+'</td><td>'+row.shadowGenerations+'</td></tr>';
}).join('');
const draws=comparison.rows.filter(r=>r.style==='dissolve').map(row=>'<tr><td>'+row.pose+'</td><td>'+row.state.draw.calls+'</td><td>'+row.state.draw.triangles.toLocaleString()+'</td><td>0</td></tr>').join('');
await writeFile(path.join(root,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grass fade comparison</title>
<style>body{margin:0;background:#15231c;color:#e7eee7;font:17px system-ui;padding:26px}main{max-width:1400px;margin:auto}h1{font-size:30px}p{max-width:1000px;line-height:1.5}a{color:#bfde9c}select,button{font:inherit;padding:7px;background:#283e2f;color:inherit;border:1px solid #789580;border-radius:5px}label{display:inline-flex;gap:10px;align-items:center;margin:6px 20px 10px 0}.compare{position:relative;aspect-ratio:1.4;overflow:hidden;background:#000}.compare img{position:absolute;width:100%;height:100%;object-fit:contain}.badge{position:absolute;top:12px;padding:8px 14px;background:#15231cdd}.right{right:12px}.left{left:12px}.divider{position:absolute;top:0;bottom:0;width:2px;background:white;left:50%}table{border-collapse:collapse;margin:15px 0 25px}td,th{padding:9px 24px 9px 0;text-align:left;border-bottom:1px solid #516453}.motion{width:100%;display:block}.note{color:#bec9be}details{margin:20px 0}input[type=range]{width:240px}</style>
<main><h1>Grass transition: preserve opaque leaf color</h1>
<p>The new default is a fine complementary opaque dissolve. It exchanges visible pixels between LODs instead of making every overlapping card translucent. Leaf cutout edges still use MSAA; transition opacity does not.</p>
<p>Plain alpha darkens the overlap and depends on draw order. Staggered card fades keep stronger leaf contrast but create clumps. The opaque dissolve best preserves the original color and spatial coverage in these three bus views.</p>
<p><a href="/debug_tools/grass_transition_scene.html?revision=opaque-dissolve-1&lod3=cards#front">Open the live scene</a> · The panel’s Fade control retains all four alternatives.</p>
<label>View <select id="pose"><option>front</option><option>rear</option><option>border</option></select></label><label>Compare with <select id="reference"><option value="coverage">Previous coverage fade</option><option value="alpha">Plain alpha</option><option value="staggered">Staggered cards</option><option value="lod3">Only LOD3</option><option value="lod4">Only LOD4</option></select></label><label>Split <input id="split" type="range" min="0" max="100" value="50"></label>
<div class="compare"><img id="old" alt="Reference grass render"><img id="current" alt="Opaque dissolve grass render"><div class="divider" id="divider"></div><span class="badge left">Opaque dissolve</span><span class="badge right" id="reference-name"></span></div>
<h2>Color and cost</h2><p class="note">Mean absolute green-channel deviation from an interpolated isolated-LOD reference, across 10–14 m in front/rear/side views (0–255 display values; lower is closer). A fixed green-pixel classifier excludes litter; this is a color proxy, not a semantic leaf mask or a proof of exact image equivalence.</p>
<table><tr><th>Fade</th><th>Color deviation</th></tr>${color}</table>
<p>Changing draw order affected ${comparison.order.find(r=>r.style==='alpha').changed.toLocaleString()} pixels with plain alpha, versus ${comparison.order.find(r=>r.style==='dissolve').changed.toLocaleString()} with the dissolve (threshold: 3/255). Depth remains writable; no transparent-card sorting is needed.</p>
<table><tr><th>Pose</th><th>Total frame draws</th><th>Triangles</th><th>Extra texture memory</th></tr>${draws}</table><p class="note">Draws and triangles exactly match the previous fade in each pose. The two card populations remain 128 MiB total. No new render targets, atlas samples, or per-card CPU updates. GPU milliseconds are not reported: other work kept GPU utilization at 100%, so a trustworthy timing comparison was unavailable.</p>
<h2>Moving bus camera</h2><label>Route <select id="route"><option>front</option><option>rear</option></select></label><button id="play">Play</button><label>Frame <input id="frame" type="range" min="0" max="39" value="0"></label><img class="motion" id="motion" alt="Moving bus camera using opaque dissolve">
<p class="note">6 m drive, 120 simulated frames at 3 m/s; every third frame captured. Same-camera cached-versus-refreshed selection is checked at 24 checkpoints per route. Counts below sum changes across those checkpoints, rather than ordinary differences between moving frames.</p><table><tr><th>Route</th><th>Dissolve rebuild changes</th><th>Patch-switch changes</th><th>Shadow rebakes</th></tr>${motion}</table>
<p><strong>Remaining tradeoffs:</strong> this is still fine pixel dithering, not ordinary alpha blending. Small grain can remain without temporal anti-aliasing. The wider LOD4 cards still have a different clump shape and LOD5 still flattens the grass; a fade cannot remove those source differences. Capturing and compositing complete LOD layers could remove transition noise, but would require additional targets and rendering passes.</p>
<details><summary>Technical basis and evidence</summary><p><a href="https://www.nvidia.com/docs/IO/88888/StochasticTransparency_I3D2010.pdf">NVIDIA: Stochastic Transparency</a> explains fixed alpha-to-coverage mask correlations and transparency ordering. This implementation uses a much simpler shared one-pixel threshold with no temporal accumulation or extra passes; it is not the paper’s full algorithm.</p><p><a href="comparison.json">Still-view measurements</a> · <a href="blending/visual.json">Eight bearings, five boundary probes, movement checks</a></p></details></main>
<script>const el=id=>document.getElementById(id);function show(){el('old').src=el('pose').value+'_'+el('reference').value+'.png';el('current').src=el('pose').value+'_dissolve.png';el('current').style.clipPath='inset(0 '+(100-Number(el('split').value))+'% 0 0)';el('divider').style.left=el('split').value+'%';el('reference-name').textContent=el('reference').selectedOptions[0].textContent;}['pose','reference','split'].forEach(id=>el(id).addEventListener('input',show));show();function move(){el('motion').src='blending/motion_'+el('route').value+'_blend_'+(Number(el('frame').value)*3)+'.jpg';}['route','frame'].forEach(id=>el(id).addEventListener('input',move));let timer;el('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;el('play').textContent='Play';}else{timer=setInterval(()=>{el('frame').value=(Number(el('frame').value)+1)%40;move();},50);el('play').textContent='Pause';}};move();</script></html>`);
console.log(path.join(root,'index.html'));
