// Present preserved rendering versions with matched camera, soil baseline and GPU comparisons.
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

export async function writeGrassLod4VersionsReport(output, report) {
    const labels = { original: 'Original · before both fixes', shadow: 'Shadow fix only', optimized: 'Interior quads + shadow fix' };
    const scenarioLabels = { lod4: 'LOD4 only + side grass', full: 'Full distances · 1 / 3 / 6 / 25 m', half: 'Half distances · 0.5 / 1.5 / 3 / 12.5 m' };
    const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
    const metric = value => `${value.averageMs.toFixed(3)}<small>95% CI ${value.ci95Ms.map(v => v.toFixed(3)).join(' to ')}</small>`;
    const root = path.relative(output, process.cwd()).replaceAll('\\', '/');
    const rows = Object.entries(report.comparisons).map(([key, entry]) => `<tr><th><button data-key="${key}">${scenarioLabels[entry.scenario]}<br>${entry.pose}</button></th>${Object.keys(labels).map(version => `<td>${metric(entry.results[version].aboveSoilGpu)}<small>${entry.captures[version].draw.triangles.toLocaleString()} triangles · ${entry.captures[version].draw.calls} draws</small></td>`).join('')}<td>${metric(entry.results.optimized.savedFromOriginalGpu)}</td><td>${metric(entry.results.optimized.savedFromShadowGpu)}</td></tr>`).join('');
    const cpuRows = Object.keys(labels).map(version => {
        const rows = report.cpuMotion.filter(row => row.version === version), average = values => values.reduce((a, b) => a + b, 0) / values.length;
        const cpu = average(rows.flatMap(row => row.cpu)), selection = average(rows.map(row => row.selectionCpuMs / 60));
        const batching = average(rows.map(row => row.batchCpuMs / 60));
        return `<tr><th>${labels[version]}</th><td>${cpu.toFixed(3)}</td><td>${selection.toFixed(4)}</td><td>${batching.toFixed(4)}</td><td>${rows.map(row => row.scans).join(' / ')}</td></tr>`;
    }).join('');
    await writeFile(path.join(output, 'index.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LOD4 · original vs interior quads</title>
<style>body{background:#15231c;color:#e6ecdf;font:16px/1.5 system-ui;margin:24px}h1{margin-bottom:6px}p{max-width:1200px}a{color:#bfdb94}select,button,input{font:inherit}button{color:inherit;background:transparent;border:0;cursor:pointer;text-align:left}button:hover{text-decoration:underline}label{display:inline-block;margin:10px 18px 10px 0}.comparison{position:relative;aspect-ratio:16/9;background:#000}.comparison img{position:absolute;inset:0;width:100%;height:100%}#candidate{clip-path:inset(0 50% 0 0)}.captions{display:flex;justify-content:space-between}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid #4a6252}small{display:block;color:#b8c9b8;font-size:12px}td{white-space:nowrap}th{font-weight:500}.scroll{overflow:auto}.note{background:#203b2a;padding:14px}</style>
<h1>LOD4: retained original, shadow fix, interior quads</h1><p>${escape(report.metadata.renderer)} · 1920 × 1080 · DPR 1 · six paired rounds per view.</p>
<p class="note"><strong>GPU times are milliseconds above matching soil-only.</strong> All versions preserve the same grass, lighting, shadows, distance assignments and 35 m side-leaf cutoff. The original restores the general shadow shader and 32-triangle cells. Shadow-only changes that shader. The new version also replaces fully enclosed LOD4 cells with two-triangle quads; exposed cells retain their existing bevels.</p>
<p><a href="${root}/debug_tools/grass_transition_scene.html?configuration=lod4-elevated-sides&revision=lod4-interior-quads-1#front">Live scene and version selector</a> · <a href="benchmark.json">Raw samples, geometry, image differences and CPU data</a>. No extra textures are created for the retained versions. The four interior instance buffers add 256 KiB; the active rendering strategy is selectable.</p>
<p><a href="../lod4_factors/index.html">Previous elevation, side-grass and shadows-disabled experiments</a> are retained unchanged. Absolute front/rear LOD4 timings vary considerably under desktop load; the paired saving columns are more useful. The geometry-only saving is not statistically conclusive for LOD4 rear or full-distance front in this run.</p>
<label>Configuration <select id="scenario">${Object.entries(scenarioLabels).map(([key, text]) => `<option value="${key}">${text}</option>`).join('')}</select></label><label>Pose <select id="pose"><option>front</option><option>rear</option><option>border</option></select></label>
<label>Left <select id="left">${Object.entries(labels).map(([key, text]) => `<option value="${key}">${text}</option>`).join('')}</select></label><label>Right <select id="right">${Object.entries(labels).map(([key, text]) => `<option value="${key}">${text}</option>`).join('')}</select></label><label>Split <input id="split" type="range" min="0" max="100" value="50"></label>
<div class="captions"><strong id="leftLabel"></strong><strong id="rightLabel"></strong></div><div class="comparison"><img id="reference" alt="Reference version"><img id="candidate" alt="Candidate version"></div><p id="difference"></p>
<div class="scroll"><table><thead><tr><th>Configuration / bus pose</th><th>Original<br>ms above soil</th><th>Shadow fix<br>ms above soil</th><th>Interior quads<br>ms above soil</th><th>Total saving<br>vs original</th><th>New saving<br>vs shadow fix</th></tr></thead><tbody>${rows}</tbody></table></div>
<h2>Moving camera CPU check</h2><p>Three 60-frame drives across 3 m at the border pose, with half distances. These use the actual production batches. Times are CPU milliseconds per frame, averaged over the complete drive; no shadow regeneration occurs.</p><div class="scroll"><table><thead><tr><th>Version</th><th>Render submission</th><th>LOD selection</th><th>Batch updates</th><th>Scans per 60 frames</th></tr></thead><tbody>${cpuRows}</tbody></table></div>
<p>${escape(report.metadata.method)} Desktop GPU clocks and load are not locked. Use the paired saving columns, rather than subtracting historical measurements. All snapshots are retained; this comparison does not overwrite earlier reports.</p>
<script>const data=${JSON.stringify(Object.fromEntries(Object.entries(report.comparisons).map(([key, entry]) => [key, Object.fromEntries(Object.keys(labels).map(version => [version, entry.captures[version].difference]))])))},labels=${JSON.stringify(labels)};const el=id=>document.getElementById(id);el('left').value='optimized';el('right').value='original';function update(){const key=el('scenario').value+'_'+el('pose').value;el('candidate').src=key+'_'+el('left').value+'.png';el('reference').src=key+'_'+el('right').value+'.png';el('candidate').style.clipPath='inset(0 '+(100-el('split').value)+'% 0 0)';el('leftLabel').textContent=labels[el('left').value];el('rightLabel').textContent=labels[el('right').value];const d=data[key].optimized;el('difference').textContent='Optimized vs original: mean RGB difference '+d.meanChannelError.toFixed(4)+' / 255; 99th-percentile pixel difference '+d.p99PixelError+' / 255.';}for(const id of ['scenario','pose','left','right','split'])el(id).addEventListener('input',update);for(const button of document.querySelectorAll('[data-key]'))button.addEventListener('click',()=>{const [scenario,pose]=button.dataset.key.split('_');el('scenario').value=scenario;el('pose').value=pose;update();document.querySelector('.comparison').scrollIntoView({behavior:'smooth'});});update();</script></html>`);
}
