#!/bin/bash
# Download Rapier.rs JavaScript 3D API documentation

BASE_URL="https://rapier.rs/javascript3d/classes"
OUTPUT_DIR="docs/rapier"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# List of all class documentation files
FILES=(
    "Ball.html"
    "BroadPhase.html"
    "CCDSolver.html"
    "Capsule.html"
    "CharacterCollision.html"
    "Collider.html"
    "ColliderDesc.html"
    "ColliderSet.html"
    "ColliderShapeCastHit.html"
    "Cone.html"
    "ConvexPolyhedron.html"
    "Cuboid.html"
    "Cylinder.html"
    "DebugRenderBuffers.html"
    "DebugRenderPipeline.html"
    "DynamicRayCastVehicleController.html"
    "EventQueue.html"
    "FixedImpulseJoint.html"
    "FixedMultibodyJoint.html"
    "GenericImpulseJoint.html"
    "HalfSpace.html"
    "Heightfield.html"
    "ImpulseJoint.html"
    "ImpulseJointSet.html"
    "IntegrationParameters.html"
    "IslandManager.html"
    "JointData.html"
    "KinematicCharacterController.html"
    "MultibodyJoint.html"
    "MultibodyJointSet.html"
    "NarrowPhase.html"
    "PhysicsPipeline.html"
    "PidController.html"
    "PointColliderProjection.html"
    "PointProjection.html"
    "Polyline.html"
    "PrismaticImpulseJoint.html"
    "PrismaticMultibodyJoint.html"
    "Quaternion.html"
    "QueryPipeline.html"
    "Ray.html"
    "RayColliderHit.html"
    "RayColliderIntersection.html"
    "RayColliderToi.html"
    "RayIntersection.html"
    "RevoluteImpulseJoint.html"
    "RevoluteMultibodyJoint.html"
    "RigidBody.html"
    "RigidBodyDesc.html"
    "RigidBodySet.html"
    "RopeImpulseJoint.html"
    "RotationOps.html"
    "RoundCone.html"
    "RoundConvexPolyhedron.html"
    "RoundCuboid.html"
    "RoundCylinder.html"
    "RoundTriangle.html"
    "SdpMatrix3.html"
    "SdpMatrix3Ops.html"
    "Segment.html"
    "SerializationPipeline.html"
    "Shape.html"
    "ShapeCastHit.html"
    "ShapeColliderTOI.html"
    "ShapeContact.html"
    "ShapeTOI.html"
    "SphericalImpulseJoint.html"
    "SphericalMultibodyJoint.html"
    "SpringImpulseJoint.html"
    "TempContactForceEvent.html"
    "TempContactManifold.html"
    "TriMesh.html"
    "Triangle.html"
    "UnitImpulseJoint.html"
    "UnitMultibodyJoint.html"
    "Vector3.html"
    "VectorOps.html"
    "Voxels.html"
    "World.html"
)

echo "Downloading Rapier.rs JavaScript 3D API documentation..."
echo "Output directory: $OUTPUT_DIR"
echo ""

# Download each file
for file in "${FILES[@]}"; do
    echo "Downloading $file..."
    curl -s -o "$OUTPUT_DIR/$file" "$BASE_URL/$file"
    sleep 0.1  # Be nice to the server
done

echo ""
echo "Download complete! Files saved to $OUTPUT_DIR"
echo "Total files: ${#FILES[@]}"

